osx_instance:
  image: high-sierra-xcode-9.4.1

task:
  timeout_in: 90m
  env: &env_targets
    matrix:
      - TARGET: lilypond
      - TARGET: lilypond-devel
  script:
    - export MACPORTS_PREFIX=/opt/${TARGET}
    - curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
    - source ./macports-ci install --prefix=${MACPORTS_PREFIX}
    - sudo port mdmg ${TARGET}
    - echo "******** Built target '${TARGET}' ********"
    - file ${MACPORTS_PREFIX}/bin/lilypond
    - echo "Work directory for ${TARGET} is $(port work ${TARGET})"
    - port contents ${TARGET}
